# Note that tasks file inside a role cannot contain a play, But only tasks

# Task 1
- name: Set VXLAN Fabric Ethernet Interfaces
  cisco.dcnm.dcnm_interface:
    fabric: "{{ vxlan_fabric_parameters.FABRIC_NAME }}"
    state: merged
    config: "{{ vxlan_ethernet_interface_list }}"
  register: result
# Task 2
- name: Set VXLAN Fabric Ethernet Interfaces Result
  ansible.builtin.debug:
    msg: "{{ result }}"

# Task 3
- name: Set VXLAN Fabric vPC Interfaces
  cisco.dcnm.dcnm_interface:
    fabric: "{{ vxlan_fabric_parameters.FABRIC_NAME }}"
    state: merged
    config: "{{ vxlan_vpc_interface_list }}"
  register: result
# Task 4
- name: Set VXLAN Fabric vPC Interfaces Result
  ansible.builtin.debug:
    msg: "{{ result }}"

# Task 5
- name: Set External Fabric Loopback Interfaces
  cisco.dcnm.dcnm_interface:
    fabric: "{{ external_fabric_parameters.FABRIC_NAME }}"
    state: merged
    config: "{{ external_loopback_interface_list }}"
  register: result
# Task 6
- name: Set External Fabric Loopback Interfaces Result
  ansible.builtin.debug:
    msg: "{{ result }}"
