# Note that tasks file inside a role cannot contain a play, But only tasks

# Task 1
- name: Create External Networks Policy
  cisco.dcnm.dcnm_policy:
    fabric: "{{ external_fabric_parameters.FABRIC_NAME }}"
    config:
      - name: bgp_vrf_network
        create_additional_policy: false
        priority: 100
        policy_vars:
          BGP_AS: "{{ external_fabric_parameters.BGP_AS }}"
          VRF_NAME: "{{ item.0.vrf_name }}"
          IP_PREFIX: "{{ item.1 }}"
      - switch:
          - ip: "{{ item.0.switch_ip }}"
  loop: "{{ lookup('subelements', vxlan_external_networks_list, 'prefixes') }}"
  register: result
# Task 2
- name: Create External Networks Policy Result
  ansible.builtin.debug:
    msg: "{{ result }}"
