---
# Play 1
- name: "Main Play"
  hosts: ndfc_host
  vars_files:
    - group_vars/fabric_vars.yml
  roles:
    - role: fabric_role
      tags:
        - tag_role_all
        - tag_role_fabric
    - role: inventory_role
      tags:
        - tag_role_all
        - tag_role_inventory
    - role: vpc_role
      tags:
        - tag_role_all
        - tag_role_vpc
    - role: interface_role
      tags:
        - tag_role_all
        - tag_role_interface
    - role: overlay_role
      tags:
        - tag_role_all
        - tag_role_overlay
    - role: vrf_lite_ext_role
      tags:
        - tag_role_all
        - tag_role_vrf_lite
    - role: ext_networks_role
      tags:
        - tag_role_all
        - tag_role_ext_networks
